import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"; 
import { Analytics } from "@vercel/analytics/react"
import Header from "../components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} >
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressContentEditableWarning suppressHydrationWarning>
        <Header/>
        {children}
        </body>
      <Analytics />
    </html>
    </ClerkProvider>

  );
}
